### ISSUE TITLE
-w always leave empty files

### ISSUE THREAD

**Issue by bortzmeyer** [dnstap/golang-dnstap#11]
dnstpa works fine for output on the screen but -w always leave me with empty files.

I tried to SIGHUP the program, to stop it with Control-C, send thousands of requests to get a buffer flush, and in all cases, the output file is created but it is empty.

**Comment by cmikk** [comment]
Greetings,

I am not able to reproduce this behavior in my testing setup. What versions of golang-dnstap and golang-framestream are you using? There have been a few recent bug fixes in both packages.

Also, are you seeing the message:

  dnstap.FrameStreamSockInput: accepted a socket connection

logged when you run `dnstap`?

**Comment by bortzmeyer** [comment]
Indeed, I did not get the message "accepted a socket connection", it works only once with Unbound, I have to restart it if I want dnstap to receive data. Strange but it seems -w is not responsible. Sorry for the false alarm.
