### ISSUE TITLE
High memory usage issue

### ISSUE THREAD

**Issue by akissa** [dnstap/golang-dnstap#18]
Hi

I have encountered an issue with high memory usage by the lib. It seems to be caused by the buffer that is being allocated using the max payload size https://github.com/farsightsec/golang-framestream/blob/master/framestream.go#L24

What is the ideal max payload size as the default is using up lots of mem.

```
(pprof) top
Showing nodes accounting for 1.16MB, 100% of 1.16MB total
      flat  flat%   sum%        cum   cum%
    1.16MB   100%   100%     1.16MB   100%  git.home.topdog-software.com/baruwa-infra/nambari/vendor/github.com/farsightsec/golang-framestream.NewDecoder
         0     0%   100%     1.16MB   100%  git.home.topdog-software.com/baruwa-infra/nambari/vendor/github.com/dnstap/golang-dnstap.(*FrameStreamSockInput).ReadInto
         0     0%   100%     1.16MB   100%  git.home.topdog-software.com/baruwa-infra/nambari/vendor/github.com/dnstap/golang-dnstap.NewFrameStreamInput
         0     0%   100%     1.16MB   100%  main.main
         0     0%   100%     1.16MB   100%  runtime.main
(pprof) list git.home.topdog-software.com/baruwa-infra/nambari/vendor/github.com/farsightsec/golang-framestream.NewDecoder
Total: 1.16MB
ROUTINE ======================== git.home.topdog-software.com/baruwa-infra/nambari/vendor/github.com/farsightsec/golang-framestream.NewDecoder in /Users/andrew/Documents/devel/go/path/src/git.home.topdog-software.com/baruwa-infra/nambari/vendor/github.com/farsightsec/golang-framestream/Decoder.go
    1.16MB     1.16MB (flat, cum)   100% of Total
         .          .     42:   }
         .          .     43:   if opt.MaxPayloadSize == 0 {
         .          .     44:       opt.MaxPayloadSize = DEFAULT_MAX_PAYLOAD_SIZE
         .          .     45:   }
         .          .     46:   dec = &Decoder{
    1.16MB     1.16MB     47:       buf:    make([]byte, opt.MaxPayloadSize),
         .          .     48:       opt:    *opt,
         .          .     49:       reader: bufio.NewReader(r),
         .          .     50:       writer: nil,
         .          .     51:   }
         .          .     52:
```

**Comment by cmikk** [comment]
The maximum size of a DNS message is 65536 bytes (based on message length fields in the TCP message format and EDNS0), so the maximum DNSTap message size should need to be only slightly larger than that. For comparison, the C language `fstrm_capture` program has a default (and formerly hardcoded) buffer size of 256 KiB.

Note that `golang-dnstap` does not provide a way to tune the buffer size / maximum message size. It should, or at least use a smaller size than 1 MiB.

**Comment by akissa** [comment]
@cmikk Thanks you have been very helpful. I will vendor the package and set a smaller buffer size.

**Comment by cmikk** [comment]
Commit 1f0a6e04cc sets the default maximum payload size to a still-generous 96KiB, but allows callers to set a lower package-wide default if needed.

Will close this issue when that is merged.
