### ISSUE TITLE
-y output is fine, -q is not

### ISSUE THREAD

**Issue by sjm42** [dnstap/golang-dnstap#2]
Input file:

19528 -rw-rw-r-- 1 dns dns 19995623 Jan  8 19:43 dnstap.20160108-194222.fs

This runs just fine:

[root@k tmp]# time /opt/unbound/sbin/dnstap -r dnstap.20160108-194222.fs -y -w koe.yaml
dnstap: opened input file dnstap.20160108-194222.fs

real    0m6.900s
user    0m6.614s
sys 0m1.071s

But this not, with the same input file:

[root@k tmp]# time /opt/unbound/sbin/dnstap -r dnstap.20160108-194222.fs -q -w koe.txt
dnstap: opened input file dnstap.20160108-194222.fs
panic: runtime error: index out of range

goroutine 6 [running]:
github.com/dnstap/golang-dnstap.textConvertMessage(0xc8203890a0, 0xc8202a4770)
    /home/sjm/gocode/src/github.com/dnstap/golang-dnstap/QuietTextFormat.go:147 +0x5b2
github.com/dnstap/golang-dnstap.TextFormat(0xc82009e000, 0x0, 0x0, 0x0, 0xc82009e000)
    /home/sjm/gocode/src/github.com/dnstap/golang-dnstap/QuietTextFormat.go:159 +0x67
github.com/dnstap/golang-dnstap.(*TextOutput).RunOutputLoop(0xc82000e480)
    /home/sjm/gocode/src/github.com/dnstap/golang-dnstap/TextOutput.go:67 +0x286
created by main.main
    /home/sjm/gocode/src/github.com/dnstap/golang-dnstap/dnstap/main.go:97 +0x409

goroutine 1 [chan receive]:
github.com/dnstap/golang-dnstap.(*FrameStreamInput).Wait(0xc820010bc0)
    /home/sjm/gocode/src/github.com/dnstap/golang-dnstap/FrameStreamInput.go:69 +0x39
main.main()
    /home/sjm/gocode/src/github.com/dnstap/golang-dnstap/dnstap/main.go:129 +0x813

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
    /home/sjm/go/src/runtime/asm_amd64.s:1721 +0x1

goroutine 5 [syscall]:
os/signal.loop()
    /home/sjm/go/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
    /home/sjm/go/src/os/signal/signal_unix.go:28 +0x37

goroutine 7 [select, locked to thread]:
runtime.gopark(0x7c4e70, 0xc820024f28, 0x747988, 0x6, 0x42d518, 0x2)
    /home/sjm/go/src/runtime/proc.go:185 +0x163
runtime.selectgoImpl(0xc820024f28, 0x0, 0x18)
    /home/sjm/go/src/runtime/select.go:392 +0xa64
runtime.selectgo(0xc820024f28)
    /home/sjm/go/src/runtime/select.go:212 +0x12
runtime.ensureSigM.func1()
    /home/sjm/go/src/runtime/signal1_unix.go:227 +0x353
runtime.goexit()
    /home/sjm/go/src/runtime/asm_amd64.s:1721 +0x1

goroutine 8 [chan receive]:
main.main.func1(0xc82000a540, 0x7f4d4c82f568, 0xc82000e480)
    /home/sjm/gocode/src/github.com/dnstap/golang-dnstap/dnstap/main.go:103 +0x4d
created by main.main
    /home/sjm/gocode/src/github.com/dnstap/golang-dnstap/dnstap/main.go:107 +0x4f5

goroutine 9 [runnable]:
syscall.Syscall(0x0, 0x4, 0xc82009d000, 0x1000, 0x1000, 0x1000, 0x0)
    /home/sjm/go/src/syscall/asm_linux_amd64.s:18 +0x5
syscall.read(0x4, 0xc82009d000, 0x1000, 0x1000, 0x4, 0x0, 0x0)
    /home/sjm/go/src/syscall/zsyscall_linux_amd64.go:783 +0x5f
syscall.Read(0x4, 0xc82009d000, 0x1000, 0x1000, 0x1000, 0x0, 0x0)
    /home/sjm/go/src/syscall/syscall_unix.go:160 +0x4d
os.(_File).read(0xc820026038, 0xc82009d000, 0x1000, 0x1000, 0x1000, 0x0, 0x0)
    /home/sjm/go/src/os/file_unix.go:211 +0x53
os.(_File).Read(0xc820026038, 0xc82009d000, 0x1000, 0x1000, 0x1000, 0x0, 0x0)
    /home/sjm/go/src/os/file.go:95 +0x8a
bufio.(_Reader).fill(0xc82000a6c0)
    /home/sjm/go/src/bufio/bufio.go:97 +0x1e9
bufio.(_Reader).Read(0xc82000a6c0, 0xc8200a2018, 0xc8, 0xfffe8, 0x18, 0x0, 0x0)
    /home/sjm/go/src/bufio/bufio.go:207 +0x260
io.ReadAtLeast(0x7f4d4c82f698, 0xc82000a6c0, 0xc8200a2000, 0xe0, 0x100000, 0xe0, 0x18, 0x0, 0x0)
    /home/sjm/go/src/io/io.go:298 +0xe6
io.ReadFull(0x7f4d4c82f698, 0xc82000a6c0, 0xc8200a2000, 0xe0, 0x100000, 0x0, 0x0, 0x0)
    /home/sjm/go/src/io/io.go:316 +0x62
github.com/farsightsec/golang-framestream.(_Decoder).readFrame(0xc820084120, 0xe0, 0x0, 0x0)
    /home/sjm/gocode/src/github.com/farsightsec/golang-framestream/Decoder.go:177 +0xcb
github.com/farsightsec/golang-framestream.(_Decoder).Decode(0xc820084120, 0x0, 0x0, 0x0, 0x0, 0x0)
    /home/sjm/gocode/src/github.com/farsightsec/golang-framestream/Decoder.go:210 +0x1d7
github.com/dnstap/golang-dnstap.(*FrameStreamInput).ReadInto(0xc820010bc0, 0xc82000a480)
    /home/sjm/gocode/src/github.com/dnstap/golang-dnstap/FrameStreamInput.go:54 +0x40
created by main.main
    /home/sjm/gocode/src/github.com/dnstap/golang-dnstap/dnstap/main.go:126 +0x7ff

real    0m0.403s
user    0m0.301s
sys 0m0.131s

[root@k tmp]# ls -las koe.*
  628 -rw-r-----  1 root dns   643050 Jan  8 19:49 koe.txt
79580 -rw-r-----  1 root dns 81486794 Jan  8 19:48 koe.yaml

**Comment by edmonds** [comment]
Hi, Sami:

This code has bitrotted somewhat, I'm not sure when I'll have time to fix this.

You might want to look at the `dnstap-ldns` repository instead: https://github.com/dnstap/dnstap-ldns. It has a C implementation of the YAML and text formatters.

**Comment by sjm42** [comment]
Yes, I understand.

My goal is to build a batch job that is processing output files from fstrm_capture offline,
and to produce some meaningful and useful statistics, anomaly alerts and stuff like that
out of the dns query data of resolvers. Abuse response team would be happy. (:

For example, which domains and/or authorative servers are receiving lots of queries
from our resolvers? Those would be mostly cache misses and thus interesting.
Which domains are giving lots of NXDOMAIN answers? Which clients have lots
of those answers on their queries? Who is asking lots of ANY queries?

For a purpose like this, I think Go language would be a good fit and this code
would provide a good basis to begin with. I would probably not try lots of
maps/hashes and generating statistics in a language like C...  (:

Cheers,

-sjm

**Comment by edmonds** [comment]
Ah, I see. So you're basically going to be using the `FrameStreamInput` type to decode the raw files, then using the protobuf definition to decode the dnstap protobufs? Then doing your analytics on the processed messages.

Very cool, please consider doing a [DNS-OARC](https://www.dns-oarc.net/) presentation if it works out well :-)

I'll try to figure out what's wrong with `QuietTextFormat`, it looks like it crashed on this line: https://github.com/dnstap/golang-dnstap/blob/master/QuietTextFormat.go#L147, which is:

```
s.WriteString("\"" + msg.Question[0].Name + "\" ")
```

Do you by chance happen to have a DNS message in your FS file that doesn't have a Question RR? Maybe something like a FORMERR response with no question section?

(If you can share the .fs file, you can send it to edmonds@fsi.io and I can take a look at it.)

**Comment by sjm42** [comment]
I would NOT be surprised of any strange or fishy queries or responses present in my data,
since it is a one-minute sample from one real production system dns node with live and actual data.

Sorry, I really am not able to share data like this for anyone outside my company/employer.

Anyway, I will share my findings when I have something of interest.

BR, -sjm

**Comment by edmonds** [comment]
OK, no problem, I have a good idea on how to test it.

**Comment by cmikk** [comment]
This should be fixed in commit ea1e39c. Will close this issue when that is merged.
