### ISSUE TITLE
Add the ability to ship text logs into a remote syslog service

### ISSUE THREAD

**Issue by elico** [dnstap/golang-dnstap#30]
Currently the -T option allow me to ship only the dnstap paylads into tcp/ip address.
I want to be able to send the text logs to a remote TCP service.
Currently what I am doing is piping the text output to a second command which forward the incoming lines to the remote server.

**Comment by haanjde** [comment]
I would like this feature too, but for all output formats. Tapping a heavily loaded server with an extra local process is sometimes too much.

**Comment by derrickhayashi** [comment]
I played around the source a little and added a `-s` flag for sending json formatted log to local syslog at https://github.com/sheepbrew/golang-dnstap/commit/ff20aa9d27370cc25a892b967d192c94115854f8. It's very much experimental and the code quality is nowhere up to any standard so I'm not going to make a PR, but it might be helpful for you.

**Comment by derrickhayashi** [comment]
So after doing all that, I realized that I can just run the app as a systemd service, which provides the option to redirect standard out/err to syslog. From there on, it’s easy to ship it off however I want it.

**Comment by mvanholsteijn** [comment]
So @sheepbrew , sounds like you can close this issue?

**Comment by derrickhayashi** [comment]
@mvanholsteijn I think it can be closed but I'm not the one who opened it. :)

**Comment by cmikk** [comment]
I believe @sheepbrew's solution, or something similar, is preferable to integrating a specific log-shipping protocol into the dnstap utility.

Closing this issue.
