### ISSUE TITLE
Breaking changes since last tagged release

### ISSUE THREAD

**Issue by dmccombs** [dnstap/golang-dnstap#31]
Since the last release in November 2018, there have been a number of breaking changes in this project for those of us that pull it in as a library used in our own code.

Could a new release tag be created to make it cleaner to pin to this version when using the new default versioned module dependency support in golang 1.13?

**Comment by cmikk** [comment]
Certainly. Would tagging the current master (0b64a38306e900a7e8a7d3137ebc6c3d1486e74c) as 0.2.0 suffice, or do you need any interim releases tagged?

**Comment by dmccombs** [comment]
A tag of current master would be enough for my instance. I suppose if you wanted to be thorough for others, you could semantically tag commits where things like the required number of arguments to functions changed that would break other's use of it as a library, or at least do that going forward. Thanks!

**Comment by cmikk** [comment]
I have tagged the current master as v0.2.0. Let me know if you need anything else.
