### ISSUE TITLE
Feature request - use go modules for dependency management

### ISSUE THREAD

**Issue by ja-pa** [dnstap/golang-dnstap#33]
I'm trying to create an OpenWrt package for dnstap-golang and I think that it would be useful to create go.mod, go.sum for the project so packaging and dependency management would be more straightforward.

something like this https://github.com/ja-pa/packages/blob/e0cacf39c57bfdd756f0df28dd442ad2d49367a3/net/dnstap/patches/go-mod.patch

**Comment by cmikk** [comment]
golang-dnstap v0.2.1 has been tagged and contains a go.mod pinning its dependencies. Thanks!

**Comment by ja-pa** [comment]
Thanks!
