### ISSUE TITLE
No query_time in DNSTAP Response message

### ISSUE THREAD

**Issue by SuperFunks** [dnstap/golang-dnstap#36]
Hi there,

I would love to be able to keep track of the performance of queries and responses going through my CoreDNS instances, and as you know i have the DNSTAP Plugin configured to point to binaries of this goland-dnstap project.

However - I think we might have missed a key part of the implementation of response messages here.

Reading through this article about response logging with DNSTAP from 2017: https://jpmens.net/2017/09/11/dns-query-response-logging-with-dnstap

It seems like we are suppose to have a query_time in our response_messages along with the response_time - so that we can diff those two and get the query/response performance.

The example from Jan-Piet Mens article:

message:
  type: TOOL_RESPONSE
  query_time: !!timestamp 1970-01-01 04:22:23.659631
  response_time: !!timestamp 1970-01-01 04:22:23.725209
  socket_family: INET
  socket_protocol: UDP
  query_address: 0.0.0.0
  response_address: 192.168.1.81
  query_port: 54370
  response_port: 53
  response_message: |
    ;; ->>HEADER<<- opcode: QUERY, rcode: NOERROR, id: 53652
    ;; flags: qr rd ra ; QUERY: 1, ANSWER: 1, AUTHORITY: 3, ADDITIONAL: 0

Been trying to poke the binary to give similar query_time on the response_messages but so far without luck - so i think the implementation of the response_message might have missed this?

Best regards

**Comment by SuperFunks** [comment]
It might be that i have misunderstood what Jan-Piet Mens is doing - maybe his use of kdig is confusing me - and is actually what is delivering the query_time in DNSTAP native format. - So it might be more advanced than the CoreDNS DNSTAP plugin.
Do you have any pointers though - to how i could get the response performance tracked?

**Comment by cmikk** [comment]
The CoreDNS dnstap plugin does not appear to include the query time in its response messages as some other servers do, which is why it is missing from the dnstap output.

Your options include:
 * sending a feature request to CoreDNS to include the query time in dnstap response reports, or
 * matching the responses to queries in the dnstap output.

**Comment by SuperFunks** [comment]
I have tried to find a reliable common link between queries and requests - but it doesnt seem to exist. - if you know of any two values that consistantly exists between the two, please let me know :)

Ill try with the feature request to CoreDNS and their plugin team.

Thanks!

**Comment by cmikk** [comment]
The query_address and query port should be the same between queries and requests, and the matching approach will additionally require parsing the encapsulated DNS message for its header ID field and query section. Note that this matching work is already done within CoreDNS, so enhancing that plugin is the preferable approach.

(The plugin code appears to keep the query timestamp around as the QueryEpoch field of the dnstap plugin ResponseWriter, but does not use it when generating response reports.)

**Comment by rdrozhdzh** [comment]
The coredns dnstap plugin uses the [dnstap.proto](https://github.com/dnstap/golang-dnstap/blob/master/dnstap.pb/dnstap.proto) defined in this project. Regarding query time it says

https://github.com/dnstap/golang-dnstap/blob/eba06ca57b59ee154df3066e774fa29775476b44/dnstap.pb/dnstap.proto#L197-L200

This comment makes an impression that this field is only required for AQ, RQ, CQ messages. I think it could be improved with a recommendation to populate this field in corresponding response messages as well.

**Comment by cmikk** [comment]
Note that the trailing commentary of dnstap.proto provides such recommendations with the preamble:

> // All fields except for 'type' in the Message schema are optional.
// It is recommended that at least the following fields be filled in for
// particular types of Messages.

and includes the query time fields in the list of recommended fields for AUTH_RESPONSE, RESOLVER_RESPONSE, and CLIENT_RESPONSE message types.

**Comment by cmikk** [comment]
Closing this issue, as it is outside golang-dnstap.
