### ISSUE TITLE
The command line tool dosen't work anymore

### ISSUE THREAD

**Issue by 2buisson** [dnstap/golang-dnstap#9]
0145fd8482619f9c04788c7ba4e96cdeef64a041 is the last working commit, *at least on my machine  :smirk:*. 

In fact the tool stops, or at least dosen't wait for [the output loop Goroutine](https://github.com/dnstap/golang-dnstap/blob/3729d1069a0097be4ff3b7e03468610171bc9d51/dnstap/main.go#L74) to finish the job.

I tried to fix the latest code, but I don't understand the new features that motivated the following commits, so why not revert to 0145fd8482619f9c04788c7ba4e96cdeef64a041?

Thanks.

**Comment by cmikk** [comment]
Can you give the 'issue9' branch a try and let us know if it works?

The subsequent commits added the desirable feature of logfile rotation, useful when collecting data from a long-running server. They appear to have broken the processing of file inputs, which `issue9` fixes.

**Comment by 2buisson** [comment]
`issue9` branch works, thank you!

**Comment by cmikk** [comment]
Fixed in #10
